version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/postgres/data 
    environment:
      - POSTGRES_USER 
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    ports:
      - "5432:5432"
  #web:
  #  build: .
  #  volumes:
  #    - .:/code
  #  ports:
  #    - "8000:8000"
  #  depends_on:
  #    - db

volumes:
  postgres_data: